[package]
name = "zerolux-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zerolux = { path = "../../../crates/zerolux" }
anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
tauri = { version = "2.12.1", features = [] }
fs2 = "0.4"
tauri-plugin-opener = "2"
serde.workspace = true
reqwest.workspace = true
tempfile = "3"
clap.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dev-dependencies]
tempfile = "3"

[features]
custom-protocol = ["tauri/custom-protocol"]
